### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by zainabz1995** [prabhakar267/ocr-convert-image-to-text#1]
when i am trying to check the module using main.py i am getting a traceback error (most recent call last at)
.....
.....
.....
![screenshot from 2017-03-30 02-59-21](https://cloud.githubusercontent.com/assets/15993688/24477522/f2bd7e84-14f4-11e7-9e1a-1c1bdaa1e675.png)

OSerror: No such file or directory

The screenshot is attached

**Comment by DipanshuSehjal** [comment]
You need to install Pillow instead of default PIL on your machine: 
cmd >> pip install pillow 
from python/scripts

**Comment by dc500** [comment]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    text = image_to_string(im)
  File "/Users/ME//Desktop/ocr-convert-image-to-text/pytesser/pytesser.py", line 30, in image_to_string
    util.image_to_scratch(im, scratch_image_name)
  File "/Users/ME/Desktop/ocr-convert-image-to-text/pytesser/util.py", line 7, in image_to_scratch
    im.save(scratch_image_name, dpi=(200,200))
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1405, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/site-packages/PIL/BmpImagePlugin.py", line 197, in _save
    raise IOError("cannot write mode %s as BMP" % im.mode)
IOError: cannot write mode RGBA as BMP

**Comment by pcakhilnadh** [comment]
I have pillow . Still getting this error why it is so ?

$ python main.py sample

/Users/pc/Downloads/ocr-convert-image-to-text-master/sample/file-page1.jpg
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    text = image_to_string(im)
  File "/Users/pc/Downloads/ocr-convert-image-to-text-master/pytesser/pytesser.py", line 31, in image_to_string
    call_tesseract(scratch_image_name, scratch_text_name_root)
  File "/Users/pc/Downloads/ocr-convert-image-to-text-master/pytesser/pytesser.py", line 21, in call_tesseract
    proc = subprocess.Popen(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by prabhakar267** [comment]
I have made some changes in commit d476fc60da9a1305bf5b2ffc398c9e99d593aecf 
That should solve this issue as well, kindly refer to the same. If anyone of you guys face any problem after updating as well, feel free to reopen this issue or open a new one.

**Comment by pcakhilnadh** [comment]
This is not resolved yet. ! Please help  me....  Im still getting No directory error 
Im trying to give path as sample 

$python main.py sample

Why there is error still ?

![screen shot 2017-09-14 at 9 37 34 am](https://user-images.githubusercontent.com/3054812/30411741-948bad98-9930-11e7-9bb3-43b285fbb1d8.png)

**Comment by prabhakar267** [comment]
@pcakhilnadh Kindly refer to #4
