### ISSUE TITLE
How to run in Windows?

### ISSUE THREAD

**Issue by justr00t** [prabhakar267/ocr-convert-image-to-text#33]
I'm trying to get this to run in windows but I keep getting this error

INFO: Could not find files for the given pattern(s).
ERROR:root:tesseract-ocr missing, use install `tesseract` to resolve.

I have installed tesseract via pip install tesseract and I *think* I added it to my system PATH variable correctly (unsure). What can I do to get it to work?

**Comment by justr00t** [comment]
I changed the PATH variable some and got this error now:

ERROR:root:Tesseract Data path Environment variable 'TESSDATA_PREFIX' needs to be configured to point to            the tessdata!

These are the PATH variables I have:

C:\Program Files (x86)\Tesseract-OCR\tessdata
C:\Program Files (x86)\Tesseract-OCR

**Comment by avsaditya** [comment]
Hi @justr00t,

You should create a new environment variable with the name TESSDATA_PREFIX with value as C:\Program Files (x86)\Tesseract-OCR\tessdata
Please let me know in cas you still face any issues.
![image](https://user-images.githubusercontent.com/17062596/47435996-3e61ee00-d7c3-11e8-8566-72d82154808f.png)

Thanks and Regards
Aditya

**Comment by siagiancp** [comment]
Hi @avsaditya , I did add TESSDATA_PREFIX to the system variable with value C:\Program Files (x86)\Tesseract-OCR\tessdata, where i install the tesseract, but I still get this error :

ERROR:root:Tesseract Data path Environment variable 'TESSDATA_PREFIX' needs to be configured to point to the tessdata!

**Comment by avsaditya** [comment]
Hi @siagiancp ,

I use os.environ to get the environment variables.
Could you just dump the output of the below from your python console"

import os
print (os.environ)
'TESSDATA_PREFIX' in os.environ
> >>> 'TESSDATA_PREFIX' in os.environ
> True

BTW, once you add the system varaible, you need to restart all active consoles for the variable to take effect. Hope you have taken care of that.

Thanks and Regards
Aditya

**Comment by moyan007** [comment]
@siagiancp you should add the path of the module directory into the system path. All things will be ok.

**Comment by avsaditya** [comment]
@siagiancp 
Still facing the issue? Do you need any help?

**Comment by siagiancp** [comment]
Thanks @avsaditya i just forgot to restart the consoles.

**Comment by prabhakar267** [comment]
I assume this issue is resolved. Closing.

**Comment by vsklearning** [comment]
I have followed the same but I am still seeing the same error

It is windows Env. Can you please help?
![image](https://user-images.githubusercontent.com/69384934/95026029-55bade80-065c-11eb-8f67-7e476851f420.png)

**Comment by prabhakar267** [comment]
@vsklearning Can you change the `TESSDATA_PREFIX` to `C:\Program Files\Tesseract-OCR\tessdata` once and then check?

**Comment by vsklearning** [comment]
Thank you. I tried this as well.  I dont see any difference. I am reinstalling all the dependencies and will try again.
